# Generated by Django 6.0 on 2026-01-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oracion',
        ),
    ]
