# Generated by Django 5.2.10 on 2026-01-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_delete_oracion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="palabramodo2",
            name="palabra_dividida_silabas",
        ),
        migrations.RemoveField(
            model_name="palabramodo2",
            name="silabas",
        ),
        migrations.AddField(
            model_name="palabramodo2",
            name="audio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="palabramodo2",
            name="opciones",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="palabramodo2",
            name="palabra_incompleta",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="palabramodo2",
            name="respuesta_correcta",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="palabrabase",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
